name: Publish Web UI Docker Image to Docker Hub

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/eat-place

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Determine Dockerfile
        id: dockerfile
        run: |
          if [ "$GITHUB_REF" == "refs/heads/prod" ]; then
            echo "Using Dockerfile.prod"
            echo "::set-output name=dockerfile::Dockerfile.prod"
          else
            echo "Using Dockerfile"
            echo "::set-output name=dockerfile::Dockerfile"
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ${{ steps.dockerfile.outputs.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          

  deploy:
    needs: build
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Trigger repo
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: eat-place
          repo: deploy
          ref: prod
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: deploy-runners.yaml
          client_payload: '{}'
          wait_interval: 11
          trigger_workflow: true
          wait_workflow: true
          propagate_failure: true
